### Crosstab functionality in pandas helps us in creating contingency tables which can be used for statistical analysis, especially for multivariate frequency distribution of variables

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Crosstab.xlsx')
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima  Bangaldesh  Female   31       Left
5    Kadir  Bangaldesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

In [4]:
# Create a table showing the handedness of people across nations
pd.crosstab(df.Nationality,df.Handedness)

Handedness   Left  Right
Nationality
Bangaldesh      2      0
China           2      1
India           2      1
USA             1      3