### Stack and unstack is another method of reshaping or transforming data

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('stocks_stackUnstack.xlsx') #if we don't provide the header argument the data looks messy as below
df

,Unnamed: 0,Price,Unnamed: 2,Unnamed: 3,Price to earning ratio(P/E),Unnamed: 5,Unnamed: 6
0,Company,Facebook,Google,Microsoft,Facebook,Google,Microsoft
1,2017-06-05 00:00:00,155,955,66,37.1,32,30.31
2,2017-06-06 00:00:00,150,987,69,36.95,31.3,30.56
3,2017-06-07 00:00:00,153,963,62,36.78,31.7,30.46
4,2017-06-08 00:00:00,155,1000,61,36.11,31.2,30.11
5,2017-06-09 00:00:00,156,1012,66,37.07,30,31

In [3]:
# use the header argument
df = pd.read_excel('stocks_stackUnstack.xlsx',header=[0,1]) # looking at the csv file,in the header we have 2 rows hence providing 0,1
df

  Unnamed: 0_level_0    Price                  Price to earning ratio(P/E)  \
             Company Facebook Google Microsoft                    Facebook
0         2017-06-05      155    955        66                       37.10
1         2017-06-06      150    987        69                       36.95
2         2017-06-07      153    963        62                       36.78
3         2017-06-08      155   1000        61                       36.11
4         2017-06-09      156   1012        66                       37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00

In [4]:
df_Stacked = df.stack(level=0) #stack the df at a chosen level, default level is -1
df_Stacked

C:\Users\ykumar4\AppData\Local\Temp\ipykernel_18576\2521714393.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_Stacked = df.stack(level=0) #stack the df at a chosen level, default level is -1

                                 Company  Facebook  Google  Microsoft
0 Price                              NaT    155.00   955.0      66.00
  Price to earning ratio(P/E)        NaT     37.10    32.0      30.31
  Unnamed: 0_level_0          2017-06-05       NaN     NaN        NaN
1 Price                              NaT    150.00   987.0      69.00
  Price to earning ratio(P/E)        NaT     36.95    31.3      30.56
  Unnamed: 0_level_0          2017-06-06       NaN     NaN        NaN
2 Price                              NaT    153.00   963.0      62.00
  Price to earning ratio(P/E)        NaT     36.78    31.7      30.46
  Unnamed: 0_level_0          2017-06-07       NaN     NaN        NaN
3 Price                              NaT    155.00  1000.0      61.00
  Price to earning ratio(P/E)        NaT     36.11    31.2      30.11
  Unnamed: 0_level_0          2017-06-08       NaN     NaN        NaN
4 Price                              NaT    156.00  1012.0      66.00
  Price to earning ratio(P/E)        NaT     37.07    30.0      31.00
  Unnamed: 0_level_0          2017-06-09       NaN     NaN        NaN